### ISSUE TITLE
Profile: Default is shown on the statusbar after selecting alternative profiles.

### ISSUE THREAD

**Issue by IP0** [robole/vscode-profile-status#2]
**Describe the bug**
After installing the extension, I clicked ono the button in the statusbar and expected it to swap profiles, which it sure did.
However it didn't swap the label on the profile, it still said "default". I've tried to read through your git but cannot seem to find a place where I would have to put the label manually and would also assume this would work automatically as shown on the gif of the market.
But no matter which profile I try to swap to, it says "Profile: default" I tried reinstalling it, I tried creating new fresh profiles, don't work.

**To Reproduce**
1. Go to 'vscode and install the extension "Profile Status" and create a new profile called 1'
* Note 1 was created after the extension was installed to check whether "old profiles" wasn't synced.
* Name of old/already existing profiles: 'C#, Default, JS, PY"
2. Click on 'the newly created profile through the extensions UI selector on the statusbar and wait for it to swap'
3. See that the profile swaps but not the label describing the profile.

**Expected behavior**
"Profile: Default" changing to "Profile: 1"

**Screenshots**
https://imgur.com/a/2UobMwf
https://prnt.sc/-hFUHXfK8owT

**Platform info (please complete the following information):**
On the main menu, select `Help` and choose `About` from the drop-down menu. Copy the information and paste it here.
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Additional context**
I absolutely love and need your extension being built into vscode! I truly hope it all will work out as intended soon or later. 
Is there any chance, you could make the static part of the label (Profile) customizable so I can hide it and only see the actual profile.

My currently biggest problem* besides what you solve! is the fact that you cannot delete or rename the built in "Default" profile.
Profiles haven't really been developed or maintained much after they introduced it and I hope they will do something about it soon.

**Comment by robole** [comment]
Hi @IP0 ,

Thanks for the feedback. I will include your screenshot inline here for easier viewing.

![screenshot](https://github.com/robole/vscode-profile-status/assets/3703647/39546cfb-d429-4cd1-bbfe-490980c1b7ce)

I use the extension every day and I have not encountered your issue.  There has been no functional changes to the extension since it was released 7 months ago. I am on Ubuntu and I tested this extension on Windows previously also, and everything was fine. It is unusual that no-one else has encountered your issue already - it is the main use case for the extension!

That suggests that there may be something specific or unique about what you are doing. Can you think of something else about your workspace/environment/situation that is different that may have triggered this? 

Some ideas:
- Did you have a workspace open?
- Do you have multiple windows open when you're changing the profile? 
- Did VS Code update in the background?
- Are you using WSL?
- ..etc.

**I will not be able to work on this issue soon because of other commitments. For now, I will leave it open for others to troubleshoot and offer a solution.** When I have time, I will circle back

Best wishes

**Comment by robole** [comment]
> My currently biggest problem* besides what you solve! is the fact that you cannot delete or rename the built in "Default" profile.

I call the mandatory base profile here as "Default" because that is what Microsoft call it. If you want different behavior around this profile,  you will need to raise it in the [vscode repo](https://github.com/microsoft/vscode).

**Comment by IP0** [comment]
No rush Rob!
I found an easy alternative: "CTRL" + "ALT" + "P" (by default opens profile switcher)
As you can see from the screenshot, the profile name is shown top right, so I'll be fine.
Thanks for your reply, this was my first ever post on Github.

**Comment by robole** [comment]
Hi @IP0 ,

I guess since this is your first post on GitHub, you do not have much experience in open source? Firstly, welcome!

If there is a potential bug,  it is preferable to leave an issue open until it investigated properly. The point of issues is to improve the software. If you close an issue before people can get to the bottom of it, it can be a waste of time. Imagine 100 people do the same thing every day?  People will not finish any work properly!

I only said that I did not have time to review the issue properly myself right now, other people who use this extension may look at the issue and help. It is a group effort. This is why I added a "help wanted" label to encourage others to look at the issue. It is fine to leave an issue open for a long period.

> I found an easy alternative: "CTRL" + "ALT" + "P" (by default opens profile switcher)

I guess you mean open the command palette which is opened by `ctrl` +` shift` + `P`, and then you selected the command `Profiles: Switch profile` to run? 

The point of the extension is not to switch profiles! The point of the extension is to show the full name of the current profile. A secondary function is to be able to switch the profile by clicking on the item in the status bar.

I responded to this so you can learn how to interact in the future in opensource. Try to learn. People are generally friendly and helpful, ask if you are not sure.

I think its best to leave the issue closed. If there is a bug, it will come up again.

Best wishes
